# Generated by Django 5.2.5 on 2025-09-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('car_model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_hobby', models.CharField(max_length=100)),
            ],
        ),
    ]
