# Generated by Django 5.2.5 on 2025-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnnyfearless', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default=0, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_available',
            field=models.BooleanField(default=True),
        ),
    ]
