# Generated by Django 5.2.5 on 2025-09-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johnnyfearless', '0003_products_product_cost_products_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_car',
        ),
    ]
