# Generated by Django 5.2.5 on 2025-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnnyfearless', '0004_delete_user_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_extradetail',
            field=models.CharField(default='Product detail.', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='product_manufacturer',
            field=models.CharField(default='Unknown.', max_length=120),
        ),
        migrations.AddField(
            model_name='products',
            name='product_team',
            field=models.CharField(default='Toronto Blue Jays', max_length=80),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=0),
        ),
    ]
